version: 2.1 
jobs:
  compile-job:
    docker:
      - image: quay.io/uuss/useedlinktoringserverbase
    resource_class: small
    steps:
      - checkout
      - run:
          name: "Configure code"
          command: |
            cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/ -DUSE_TBB=ON -DBUILD_CONTAINER=ON
      - run:
          name: "Build the code"
          command: |
            cmake --build build
      - run:
          name: "Test the code"
          command: |
            ctest --test-dir build --verbose
      - run:
          name: "Package code"
          command: |
            cd build
            mkdir -p /tmp/artifacts
            mkdir -p /tmp/workspace
            cpack -B /tmp/artifacts TGZ 
            rm -rf /tmp/artifacts/_CPack_Packages
            cp /tmp/artifacts/*-Linux.tar.gz /tmp/workspace/
            cp Dockerfile.u24 /tmp/workspace/
            ls /tmp/workspace/
      - run:
          name: "Copy ringserver"
          command: |
            cp /usr/local/bin/ringserver /tmp/workspace
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - Dockerfile.u24
            - uSEEDLinkToRingServer-*
            - ringserver
  # End compile job
  deploy-job:
    docker:
      - image: cimg/base:2022.09
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Quay login"
          command: |
            docker login -u="${QUAY_ROBOT_USER}" -p="${QUAY_ROBOT_PASSWORD}" quay.io
      - run:
          name: "Create docker image and upload"
          command: |
            #ls /tmp/workspace/
            cd /tmp/workspace
            #ls
            # Figure out version from app-name-MAJOR.MINOR.PATCH-Linux.tar.gz
            tarFile=$(ls *Linux.tar.gz)
            version=$(echo ${tarFile} | sed 's/uDataPacketService-//g' | sed 's/-Linux.tar.gz//g')
            #echo ${version}
            docker build -t useedlinktoringserver:${version} -t useedlinktoringserver:latest -f ./Dockerfile.u24 .
            docker tag useedlinktoringserver:${version} quay.io/uuss/useedlinktoringserver:${version}
            docker push quay.io/uuss/useedlinktoringserver:${version}
    # end steps
  # end deploy job

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  compile-workflow:
    jobs:
      - compile-job
      - deploy-job:
          requires:
            - compile-job
