# Purpose: Creates the container for running the uDataPacketService software
#          in an Ubuntu container.
# Usage: podman build -t useedlinktoringserver:latest -f Dockerfile.u24
#        buildah bud -t useedlinktoringserver:latest -f Dockerfile.u24
FROM ubuntu:24.04
COPY @PROJECT_NAME@-@PROJECT_VERSION@-Linux.tar.gz .
COPY /usr/local/bin/ringserver .
LABEL version="@PROJECT_VERSION@"
RUN apt-get update &&\
    apt-get upgrade -y &&\
    apt-get autoremove -y &&\
    apt-get autoclean -y &&\
    apt-get -y install bash &&\
    apt-get -y install libcurl4-openssl-dev &&\
    apt-get -y install libtbb-dev &&\
    apt-get autoremove -y &&\
    apt-get clean &&\
    tar -xf ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux.tar.gz &&\
    mv ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux/bin/uSEEDLinkToRingServer /usr/local/bin &&\
    mv ringserver /usr/local/bin &&\
    rm -r ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux/ &&\
    rm -r /var/lib/apt/lists/* ./@PROJECT_NAME@-@PROJECT_VERSION@-Linux.tar.gz

RUN useradd -ms /bin/bash us8 
USER us8
WORKDIR /home/us8

#CMD /usr/local/bin/uDataPacketService --config=service.ini

